# Generated by Django 5.1.2 on 2024-12-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='twitter_access_token_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
